[workspace]
resolver = "2"
members = [
    "crates/nxpu-parser",
    "crates/nxpu-ir",
    "crates/nxpu-opt",
    "crates/nxpu-backend-core",
    "crates/nxpu-backend-onnx",
    "crates/nxpu-backend-tflite",
    "crates/nxpu-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
