[package]
name = "nxpu-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nxpu-ir = { path = "../nxpu-ir" }
nxpu-backend-core = { path = "../nxpu-backend-core" }
thiserror.workspace = true
