[package]
name = "nxpu-parser"
description = "WGSL parser for NxPU"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
naga = { version = "28", features = ["wgsl-in"] }
nxpu-ir = { path = "../nxpu-ir" }
thiserror = "2"
